//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Administracion.ServicioFarma {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Farmaceutica", Namespace="http://schemas.datacontract.org/2004/07/Entidades_Compartidas")]
    [System.SerializableAttribute()]
    public partial class Farmaceutica : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CorreoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DirFiscField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomFarField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TelefonoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Correo {
            get {
                return this.CorreoField;
            }
            set {
                if ((object.ReferenceEquals(this.CorreoField, value) != true)) {
                    this.CorreoField = value;
                    this.RaisePropertyChanged("Correo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DirFisc {
            get {
                return this.DirFiscField;
            }
            set {
                if ((object.ReferenceEquals(this.DirFiscField, value) != true)) {
                    this.DirFiscField = value;
                    this.RaisePropertyChanged("DirFisc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NomFar {
            get {
                return this.NomFarField;
            }
            set {
                if ((object.ReferenceEquals(this.NomFarField, value) != true)) {
                    this.NomFarField = value;
                    this.RaisePropertyChanged("NomFar");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Telefono {
            get {
                return this.TelefonoField;
            }
            set {
                if ((this.TelefonoField.Equals(value) != true)) {
                    this.TelefonoField = value;
                    this.RaisePropertyChanged("Telefono");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Usuario", Namespace="http://schemas.datacontract.org/2004/07/Entidades_Compartidas")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Administracion.ServicioFarma.Empleado))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Administracion.ServicioFarma.Encargado))]
    public partial class Usuario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContraField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomComField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomUserField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Ci {
            get {
                return this.CiField;
            }
            set {
                if ((this.CiField.Equals(value) != true)) {
                    this.CiField = value;
                    this.RaisePropertyChanged("Ci");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Contra {
            get {
                return this.ContraField;
            }
            set {
                if ((object.ReferenceEquals(this.ContraField, value) != true)) {
                    this.ContraField = value;
                    this.RaisePropertyChanged("Contra");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NomCom {
            get {
                return this.NomComField;
            }
            set {
                if ((object.ReferenceEquals(this.NomComField, value) != true)) {
                    this.NomComField = value;
                    this.RaisePropertyChanged("NomCom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NomUser {
            get {
                return this.NomUserField;
            }
            set {
                if ((object.ReferenceEquals(this.NomUserField, value) != true)) {
                    this.NomUserField = value;
                    this.RaisePropertyChanged("NomUser");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Empleado", Namespace="http://schemas.datacontract.org/2004/07/Entidades_Compartidas")]
    [System.SerializableAttribute()]
    public partial class Empleado : Administracion.ServicioFarma.Usuario {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FinField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InicioField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Fin {
            get {
                return this.FinField;
            }
            set {
                if ((object.ReferenceEquals(this.FinField, value) != true)) {
                    this.FinField = value;
                    this.RaisePropertyChanged("Fin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Inicio {
            get {
                return this.InicioField;
            }
            set {
                if ((object.ReferenceEquals(this.InicioField, value) != true)) {
                    this.InicioField = value;
                    this.RaisePropertyChanged("Inicio");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Encargado", Namespace="http://schemas.datacontract.org/2004/07/Entidades_Compartidas")]
    [System.SerializableAttribute()]
    public partial class Encargado : Administracion.ServicioFarma.Usuario {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TelefonoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Telefono {
            get {
                return this.TelefonoField;
            }
            set {
                if ((this.TelefonoField.Equals(value) != true)) {
                    this.TelefonoField = value;
                    this.RaisePropertyChanged("Telefono");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Medicamento", Namespace="http://schemas.datacontract.org/2004/07/Entidades_Compartidas")]
    [System.SerializableAttribute()]
    public partial class Medicamento : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomMedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PrecioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StockField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Administracion.ServicioFarma.Farmaceutica UnaFarmaceuticaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((this.CodigoField.Equals(value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Desc {
            get {
                return this.DescField;
            }
            set {
                if ((object.ReferenceEquals(this.DescField, value) != true)) {
                    this.DescField = value;
                    this.RaisePropertyChanged("Desc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NomMed {
            get {
                return this.NomMedField;
            }
            set {
                if ((object.ReferenceEquals(this.NomMedField, value) != true)) {
                    this.NomMedField = value;
                    this.RaisePropertyChanged("NomMed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Precio {
            get {
                return this.PrecioField;
            }
            set {
                if ((this.PrecioField.Equals(value) != true)) {
                    this.PrecioField = value;
                    this.RaisePropertyChanged("Precio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Stock {
            get {
                return this.StockField;
            }
            set {
                if ((this.StockField.Equals(value) != true)) {
                    this.StockField = value;
                    this.RaisePropertyChanged("Stock");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tipo {
            get {
                return this.TipoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoField, value) != true)) {
                    this.TipoField = value;
                    this.RaisePropertyChanged("Tipo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Administracion.ServicioFarma.Farmaceutica UnaFarmaceutica {
            get {
                return this.UnaFarmaceuticaField;
            }
            set {
                if ((object.ReferenceEquals(this.UnaFarmaceuticaField, value) != true)) {
                    this.UnaFarmaceuticaField = value;
                    this.RaisePropertyChanged("UnaFarmaceutica");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PedidoCabezal", Namespace="http://schemas.datacontract.org/2004/07/Entidades_Compartidas")]
    [System.SerializableAttribute()]
    public partial class PedidoCabezal : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DirEtgaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FecRealField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Administracion.ServicioFarma.PedidosLinea[] LineasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumeroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Administracion.ServicioFarma.Empleado UnEmpField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DirEtga {
            get {
                return this.DirEtgaField;
            }
            set {
                if ((object.ReferenceEquals(this.DirEtgaField, value) != true)) {
                    this.DirEtgaField = value;
                    this.RaisePropertyChanged("DirEtga");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoField, value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FecReal {
            get {
                return this.FecRealField;
            }
            set {
                if ((this.FecRealField.Equals(value) != true)) {
                    this.FecRealField = value;
                    this.RaisePropertyChanged("FecReal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Administracion.ServicioFarma.PedidosLinea[] Lineas {
            get {
                return this.LineasField;
            }
            set {
                if ((object.ReferenceEquals(this.LineasField, value) != true)) {
                    this.LineasField = value;
                    this.RaisePropertyChanged("Lineas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Numero {
            get {
                return this.NumeroField;
            }
            set {
                if ((this.NumeroField.Equals(value) != true)) {
                    this.NumeroField = value;
                    this.RaisePropertyChanged("Numero");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Administracion.ServicioFarma.Empleado UnEmp {
            get {
                return this.UnEmpField;
            }
            set {
                if ((object.ReferenceEquals(this.UnEmpField, value) != true)) {
                    this.UnEmpField = value;
                    this.RaisePropertyChanged("UnEmp");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PedidosLinea", Namespace="http://schemas.datacontract.org/2004/07/Entidades_Compartidas")]
    [System.SerializableAttribute()]
    public partial class PedidosLinea : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CantField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Administracion.ServicioFarma.Medicamento UnMedicamentoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Cant {
            get {
                return this.CantField;
            }
            set {
                if ((this.CantField.Equals(value) != true)) {
                    this.CantField = value;
                    this.RaisePropertyChanged("Cant");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Administracion.ServicioFarma.Medicamento UnMedicamento {
            get {
                return this.UnMedicamentoField;
            }
            set {
                if ((object.ReferenceEquals(this.UnMedicamentoField, value) != true)) {
                    this.UnMedicamentoField = value;
                    this.RaisePropertyChanged("UnMedicamento");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioFarma.IServicioWCF")]
    public interface IServicioWCF {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioWCF/AltaFarmaceutica", ReplyAction="http://tempuri.org/IServicioWCF/AltaFarmaceuticaResponse")]
        void AltaFarmaceutica(Administracion.ServicioFarma.Farmaceutica unaFarmaceutica, Administracion.ServicioFarma.Encargado unEncargado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioWCF/EliminarFarmaceutica", ReplyAction="http://tempuri.org/IServicioWCF/EliminarFarmaceuticaResponse")]
        void EliminarFarmaceutica(Administracion.ServicioFarma.Farmaceutica unaFarmaceutica, Administracion.ServicioFarma.Encargado unEncargado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioWCF/ModificarFarmaceutica", ReplyAction="http://tempuri.org/IServicioWCF/ModificarFarmaceuticaResponse")]
        void ModificarFarmaceutica(Administracion.ServicioFarma.Farmaceutica unaFarmaceutica, Administracion.ServicioFarma.Encargado unEncargado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioWCF/BuscarFarmaceuticaActiva", ReplyAction="http://tempuri.org/IServicioWCF/BuscarFarmaceuticaActivaResponse")]
        Administracion.ServicioFarma.Farmaceutica BuscarFarmaceuticaActiva(string pnombre, Administracion.ServicioFarma.Usuario unUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioWCF/ListarFarmaceuticasActivas", ReplyAction="http://tempuri.org/IServicioWCF/ListarFarmaceuticasActivasResponse")]
        Administracion.ServicioFarma.Farmaceutica[] ListarFarmaceuticasActivas(Administracion.ServicioFarma.Encargado unEncargado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioWCF/AgregarMedicamentos", ReplyAction="http://tempuri.org/IServicioWCF/AgregarMedicamentosResponse")]
        void AgregarMedicamentos(Administracion.ServicioFarma.Medicamento M, Administracion.ServicioFarma.Encargado E);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioWCF/EliminarMedicamentos", ReplyAction="http://tempuri.org/IServicioWCF/EliminarMedicamentosResponse")]
        void EliminarMedicamentos(Administracion.ServicioFarma.Medicamento M, Administracion.ServicioFarma.Encargado E);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioWCF/ModificarMedicamentos", ReplyAction="http://tempuri.org/IServicioWCF/ModificarMedicamentosResponse")]
        void ModificarMedicamentos(Administracion.ServicioFarma.Medicamento M, Administracion.ServicioFarma.Encargado E);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioWCF/MedicamentosStock", ReplyAction="http://tempuri.org/IServicioWCF/MedicamentosStockResponse")]
        string MedicamentosStock();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioWCF/BuscarMedicamentosActivos", ReplyAction="http://tempuri.org/IServicioWCF/BuscarMedicamentosActivosResponse")]
        Administracion.ServicioFarma.Medicamento BuscarMedicamentosActivos(Administracion.ServicioFarma.Farmaceutica pnombreF, int pcodigo, Administracion.ServicioFarma.Usuario unUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioWCF/ListarMedicamentosActivos", ReplyAction="http://tempuri.org/IServicioWCF/ListarMedicamentosActivosResponse")]
        Administracion.ServicioFarma.Medicamento[] ListarMedicamentosActivos(Administracion.ServicioFarma.Encargado unEncargado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioWCF/ListaPedidosEsteAno", ReplyAction="http://tempuri.org/IServicioWCF/ListaPedidosEsteAnoResponse")]
        Administracion.ServicioFarma.PedidoCabezal[] ListaPedidosEsteAno(Administracion.ServicioFarma.Encargado pEncargado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioWCF/ListaPedidosGeneradoEnviado", ReplyAction="http://tempuri.org/IServicioWCF/ListaPedidosGeneradoEnviadoResponse")]
        Administracion.ServicioFarma.PedidoCabezal[] ListaPedidosGeneradoEnviado(Administracion.ServicioFarma.Encargado pEncargado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioWCF/BuscarPedido", ReplyAction="http://tempuri.org/IServicioWCF/BuscarPedidoResponse")]
        Administracion.ServicioFarma.PedidoCabezal BuscarPedido(int pCodigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioWCF/AltaPedido", ReplyAction="http://tempuri.org/IServicioWCF/AltaPedidoResponse")]
        void AltaPedido(Administracion.ServicioFarma.PedidoCabezal pPedido);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioWCF/CambioDeEstado", ReplyAction="http://tempuri.org/IServicioWCF/CambioDeEstadoResponse")]
        void CambioDeEstado(Administracion.ServicioFarma.PedidoCabezal pPedido, string pEstadoNuevo, Administracion.ServicioFarma.Encargado E);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioWCF/AgregarUsuario", ReplyAction="http://tempuri.org/IServicioWCF/AgregarUsuarioResponse")]
        void AgregarUsuario(Administracion.ServicioFarma.Usuario U, Administracion.ServicioFarma.Encargado encargadoAutorizante);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioWCF/EliminarUsuario", ReplyAction="http://tempuri.org/IServicioWCF/EliminarUsuarioResponse")]
        void EliminarUsuario(Administracion.ServicioFarma.Usuario U, Administracion.ServicioFarma.Encargado encargadoAutorizante);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioWCF/ModificarUsuario", ReplyAction="http://tempuri.org/IServicioWCF/ModificarUsuarioResponse")]
        void ModificarUsuario(Administracion.ServicioFarma.Usuario U, Administracion.ServicioFarma.Encargado encargadoAutorizante);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioWCF/CambioContrasena", ReplyAction="http://tempuri.org/IServicioWCF/CambioContrasenaResponse")]
        void CambioContrasena(Administracion.ServicioFarma.Usuario pUsuario, string newContrasena);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioWCF/Login", ReplyAction="http://tempuri.org/IServicioWCF/LoginResponse")]
        Administracion.ServicioFarma.Usuario Login(string pNombreUsuario, string pContrasena);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioWCF/BuscarUsuariosActivos", ReplyAction="http://tempuri.org/IServicioWCF/BuscarUsuariosActivosResponse")]
        Administracion.ServicioFarma.Usuario BuscarUsuariosActivos(int pci, Administracion.ServicioFarma.Encargado encargadoAutorizante);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioWCF/AgregaHorasExtras", ReplyAction="http://tempuri.org/IServicioWCF/AgregaHorasExtrasResponse")]
        void AgregaHorasExtras(int pCi, System.DateTime pFecha, int pMinutos);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioWCFChannel : Administracion.ServicioFarma.IServicioWCF, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioWCFClient : System.ServiceModel.ClientBase<Administracion.ServicioFarma.IServicioWCF>, Administracion.ServicioFarma.IServicioWCF {
        
        public ServicioWCFClient() {
        }
        
        public ServicioWCFClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioWCFClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioWCFClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioWCFClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void AltaFarmaceutica(Administracion.ServicioFarma.Farmaceutica unaFarmaceutica, Administracion.ServicioFarma.Encargado unEncargado) {
            base.Channel.AltaFarmaceutica(unaFarmaceutica, unEncargado);
        }
        
        public void EliminarFarmaceutica(Administracion.ServicioFarma.Farmaceutica unaFarmaceutica, Administracion.ServicioFarma.Encargado unEncargado) {
            base.Channel.EliminarFarmaceutica(unaFarmaceutica, unEncargado);
        }
        
        public void ModificarFarmaceutica(Administracion.ServicioFarma.Farmaceutica unaFarmaceutica, Administracion.ServicioFarma.Encargado unEncargado) {
            base.Channel.ModificarFarmaceutica(unaFarmaceutica, unEncargado);
        }
        
        public Administracion.ServicioFarma.Farmaceutica BuscarFarmaceuticaActiva(string pnombre, Administracion.ServicioFarma.Usuario unUsuario) {
            return base.Channel.BuscarFarmaceuticaActiva(pnombre, unUsuario);
        }
        
        public Administracion.ServicioFarma.Farmaceutica[] ListarFarmaceuticasActivas(Administracion.ServicioFarma.Encargado unEncargado) {
            return base.Channel.ListarFarmaceuticasActivas(unEncargado);
        }
        
        public void AgregarMedicamentos(Administracion.ServicioFarma.Medicamento M, Administracion.ServicioFarma.Encargado E) {
            base.Channel.AgregarMedicamentos(M, E);
        }
        
        public void EliminarMedicamentos(Administracion.ServicioFarma.Medicamento M, Administracion.ServicioFarma.Encargado E) {
            base.Channel.EliminarMedicamentos(M, E);
        }
        
        public void ModificarMedicamentos(Administracion.ServicioFarma.Medicamento M, Administracion.ServicioFarma.Encargado E) {
            base.Channel.ModificarMedicamentos(M, E);
        }
        
        public string MedicamentosStock() {
            return base.Channel.MedicamentosStock();
        }
        
        public Administracion.ServicioFarma.Medicamento BuscarMedicamentosActivos(Administracion.ServicioFarma.Farmaceutica pnombreF, int pcodigo, Administracion.ServicioFarma.Usuario unUsuario) {
            return base.Channel.BuscarMedicamentosActivos(pnombreF, pcodigo, unUsuario);
        }
        
        public Administracion.ServicioFarma.Medicamento[] ListarMedicamentosActivos(Administracion.ServicioFarma.Encargado unEncargado) {
            return base.Channel.ListarMedicamentosActivos(unEncargado);
        }
        
        public Administracion.ServicioFarma.PedidoCabezal[] ListaPedidosEsteAno(Administracion.ServicioFarma.Encargado pEncargado) {
            return base.Channel.ListaPedidosEsteAno(pEncargado);
        }
        
        public Administracion.ServicioFarma.PedidoCabezal[] ListaPedidosGeneradoEnviado(Administracion.ServicioFarma.Encargado pEncargado) {
            return base.Channel.ListaPedidosGeneradoEnviado(pEncargado);
        }
        
        public Administracion.ServicioFarma.PedidoCabezal BuscarPedido(int pCodigo) {
            return base.Channel.BuscarPedido(pCodigo);
        }
        
        public void AltaPedido(Administracion.ServicioFarma.PedidoCabezal pPedido) {
            base.Channel.AltaPedido(pPedido);
        }
        
        public void CambioDeEstado(Administracion.ServicioFarma.PedidoCabezal pPedido, string pEstadoNuevo, Administracion.ServicioFarma.Encargado E) {
            base.Channel.CambioDeEstado(pPedido, pEstadoNuevo, E);
        }
        
        public void AgregarUsuario(Administracion.ServicioFarma.Usuario U, Administracion.ServicioFarma.Encargado encargadoAutorizante) {
            base.Channel.AgregarUsuario(U, encargadoAutorizante);
        }
        
        public void EliminarUsuario(Administracion.ServicioFarma.Usuario U, Administracion.ServicioFarma.Encargado encargadoAutorizante) {
            base.Channel.EliminarUsuario(U, encargadoAutorizante);
        }
        
        public void ModificarUsuario(Administracion.ServicioFarma.Usuario U, Administracion.ServicioFarma.Encargado encargadoAutorizante) {
            base.Channel.ModificarUsuario(U, encargadoAutorizante);
        }
        
        public void CambioContrasena(Administracion.ServicioFarma.Usuario pUsuario, string newContrasena) {
            base.Channel.CambioContrasena(pUsuario, newContrasena);
        }
        
        public Administracion.ServicioFarma.Usuario Login(string pNombreUsuario, string pContrasena) {
            return base.Channel.Login(pNombreUsuario, pContrasena);
        }
        
        public Administracion.ServicioFarma.Usuario BuscarUsuariosActivos(int pci, Administracion.ServicioFarma.Encargado encargadoAutorizante) {
            return base.Channel.BuscarUsuariosActivos(pci, encargadoAutorizante);
        }
        
        public void AgregaHorasExtras(int pCi, System.DateTime pFecha, int pMinutos) {
            base.Channel.AgregaHorasExtras(pCi, pFecha, pMinutos);
        }
    }
}
